name: Conventional Commit
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  validate_pr_title:
    uses: https://git.tainton.uk/actions/gha-workflows/.gitea/workflows/conventional-commit.yml@main
    with:
      commit_message: ${{ gitea.event.pull_request.title }}
