name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create_release:
    name: Create Release
    uses: https://git.tainton.uk/actions/gha-workflows/.gitea/workflows/create-release.yml@main
    secrets:
      ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}

  print_release:
    name: Print Release
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - run: echo "Created release ${{ needs.create_release.outputs.release_name }}."
